### ISSUE TITLE
feature: preview-responses

### ISSUE THREAD

**Issue by 0x303** [BishopFox/sj#16]
Within the automate subcommand it would be nice to have a `--preview-responses` flag to be able to print out the response of each request rather than just the status code. 

Since some of the responses can be really long it would probably be a good idea to limit the length to a certain number of chars or bytes by default and perhaps add a `--preview-length` flag to be able to adjust this length.

Perhaps doing `sj automate -u <url_spec_file> --preview-responses --preview-length FULL` would be a way for you to show the entire response.

**Comment by twest-bf** [comment]
Implemented in e22c11c.
