### ISSUE TITLE
Standardize output of automate command across consecutive runs with `--sort` and `--group`

### ISSUE THREAD

**Issue by 0x303** [BishopFox/sj#21]
Currently, running the same `sj automate -u https://example.com/v1/swagger.json` multiple times in a row will make the same API requests, but in a different order across runs. This will effectively produce a different output from one run to the next, which makes it hard to visually tell the difference between outputs when tweaking your command or comparing across more than one hosts. 

I think it would make much more sense to do both:

1. Alphabetical sorting of requests.
2. Grouping by request method type (GET, POST, etc). 

This way you could use a `--sort` to sort all calls alphabetically, a `--group` to group by request method, or use both `--sort` and `--group` to sort all methods and then assemble into groups by request method.

**Comment by twest-bf** [comment]
This was partially fixed in 530143b - requests are now automatically sorted for JSON output. Still working on sorting them when output is logged directly to the terminal.

**Comment by twest-bf** [comment]
Console output is now also auto-sorted in cc99aef. Closing for now - may add grouping by method at a later time.
