### ISSUE TITLE
Use the internal spec file conversion feature to convert and save remote spec files to a standardized format

### ISSUE THREAD

**Issue by 0x303** [BishopFox/sj#23]
Currently, you can use the `--output` flag to save a copy of the spec file locally and `sj` automatically converts it to a standard format (openapi 3.0.1 I believe).

There are certain cases where it would be nice to utilize this feature to simply grab and save a converted spec file locally without having to first use the `automate` or `brute` subcommands, which are currently the only subcommands that support that `--output` flag. 

I propose adding a `convert` subcommand that will simply accept a remote specfile (or perhaps a local file) location and then use `sj` to convert the file and save it in the standardized format.

**Comment by twest-bf** [comment]
Implemented in 291edfe.
