### ISSUE TITLE
Failing to Write Complete Log to Output

### ISSUE THREAD

**Issue by tayari-bf** [BishopFox/sj#24]
**Describe the bug**
When attempting to run `sj automate` and have the output be logged to a file, `sj` outputs some initial results to the file and then it somehow closes the file early as an error is outputted stating that it failed to write to log as the file is already closed.

`sj` then proceeds to hang indefinitely.

This is on the latest version, version 1.7.2.

**To Reproduce**
1. Run `sj automate` specifying an output file and the output type to be JSON.

**Expected behavior**
Expected the output file to contain all the JSON results however, an initial set of results is outputted to the output file before the error is outputted and the program hangs.

**Console Logs**
```
sj automate  -u "https://example.swagger/swagger/docs/v1" -o sj-output.json -F json
WARN[0000] Note: To avoid these messages, pass the quiet (-q) flag. 

Failed to write to log, write sj-output.json: file already closed
```

**Additional context**
N/A

**Comment by twest-bf** [comment]
This is (hopefully) fixed in 615f0c7. Feel free to re-open the issue if the issue still exists!
