### ISSUE TITLE
how can I resolve this

### ISSUE THREAD

**Issue by kashif979** [BishopFox/sj#30]
![Screenshot (608)](https://github.com/user-attachments/assets/c4198b21-6d4e-468e-9f91-2ff6e8dc6a97)

**Comment by twest-bf** [comment]
It seems like the definition file may be invalid, but it's hard to say without seeing the content of the definition file. Feel free to reopen if you can provide more information.

**Comment by kashif979** [comment]
I wrote the URL of the . json. The content of the file is:
![Screenshot (609)](https://github.com/user-attachments/assets/6396234d-845a-4770-b56e-dbad917a74f8)
