### ISSUE TITLE
sj convert --force flag to force download when specification file is already in v3 format.

### ISSUE THREAD

**Issue by 0x303** [BishopFox/sj#35]
I ran into an issue recently where I was counting on `sj convert` to download a file in an automation pipeline and was confronted with this error message:
```
$ sj convert -q -i -t 60 -u https://fakewebsite.com/swagger/v1/swagger.json -o /tmp/fakewebsite.com.json

INFO[0000] Gathering API details.
                      
FATA[0001] Definition file is already version 3.
```

So then the copy of the specification file was not saved locally. I know that I can simply use `curl` to hit that endpoint again and save a copy of the file, but for simplicity purposes I would love to see a `--force` flag for the `sj convert` subcommand to force it to save the specification file locally (when passing the `-o` argument) even when it is already in version 3 format. 

This would provide a much more reliable way to use this in an automation pipeline.

**Comment by twest-bf** [comment]
Fixed in a9f907e.
